### ISSUE TITLE
Feature request: Add compatibliity for zzromtool

### ISSUE THREAD

**Issue by ariahiro64** [sauraen/seq64#12]
zzromtool allows you to manage files instead of work with a raw legend of zelda debug rom. in the past i would have to redump code the audio table sound table and sequence table and transplant.
implimenting it would just mean to find the .zzrp file as files are always in the same directory.
![image](https://user-images.githubusercontent.com/45049787/70770622-1f624a80-1d3c-11ea-9ae8-fcd66379a410.png)
![image](https://user-images.githubusercontent.com/45049787/70770640-2c7f3980-1d3c-11ea-8a68-5f2531b2ad2d.png)
![image](https://user-images.githubusercontent.com/45049787/70770648-343ede00-1d3c-11ea-8fe3-3de90014ec8c.png)
these are the only folders you need to worry about. https://wiki.cloudmodding.com/oot/File_List/Debug should assist finding the offsets from the start of the file as you just do rom offset-start of file in vrom.

**Comment by sauraen** [comment]
This is a planned feature. I recently became aware of zzromtool and I think this is the way of the future. SEQ64 will read/write code as well as audiobank and audioseq, since the four indexes (tables) (Audiobank Index, Audioseq Index, Audiotable Index, Seq Banks Map aka Instrument Set Index) are in code.

SEQ64 supports all ROM versions as well as hacked ROMs via custom romdesc files. So, the feature would require copied romdesc files for the zzromtool filesystem, specifying the offsets of the relevant indexes within code from the start of code (rather than from the start of the ROM as they normally are). Finding audiobank/audioseq will not be a problem of course.

**Comment by sauraen** [comment]
This is moot as since this was posted zzromtool has become zzrtl, and the community has moved away from both of them in favor of decomp. Anyway, SEQ64 V2.0 together with https://github.com/sauraen/AudiobankToC mostly provide the requested features.
