### ISSUE TITLE
pitch bend data is lost/changed on export/reimport

### ISSUE THREAD

**Issue by darkychao** [sauraen/seq64#15]
exporting a sequence to midi will always export to a 6 bend range and will clip all values that are between 0x7f-0x40 and 0xC0-0x80.
importing a midi to sequence will always assume a 12 bend range, effectively meaning that importing any midi exported using this program will have their bend values multiplied by 2.

the bend range box is useless and does nothing other than change the data entry MSB command value at the start of all of the midi channels.

**Comment by sauraen** [comment]
Hi, thanks for the bug report!
It seems the MIDI export code was in error. This was very old code, so I don't remember exactly what I was thinking, but I think I must have been assuming that pitch bend commands were limited to a 7-bit range like other CCs, and therefore that the only valid values would be 0xC0-0x3F. The "clipping" was a safety to make sure that the outputs were in range (without the clipping, the results might have wrapped and been even worse). But this isn't true, we now know pitch bend is 8 bit.
Also at that time, a lot was still unknown about sequence files, and I was always looking for the magic value somewhere in the header or the unknown commands that would set the pitch bend range. Now, it doesn't seem to exist at all--pitch bends are just a range of 12 always. This makes sense, because a range of 6 with values multiplied by 2 gives the same results as a range of 12, except for the values which were getting clipped before. I do remember some weird export mistakes on the pitch bends in Lon Lon Ranch, this would explain that.
I've fixed the MIDI export, removed the bend range box and set the RPN to always set the bend range to 12 on export. This is in the "SEQ64 v2.0" in development which supports full MIDI <-> .mus (MML) <-> .com (Audioseq) import/export for use with zzrtl and other toolchains, and all the decomped SM64 sequence commands, including all the dynamic sequence stuff. The sequence portion of SEQ64 v2.0 is expected to release sometime in the coming weeks (hopefully); the corresponding functionality for banks and Audiotable will be many months after that.
