### ISSUE TITLE
doesnt work with m64 files

### ISSUE THREAD

**Issue by UnknownSkid** [sauraen/seq64#29]
doesnt work with m64 files, how am i supposed to use this if it cant load the main file that the songs use, what even is .mus and .cum

you should make this work with the pc port

**Comment by sauraen** [comment]
SEQ64 absolutely works with .m64 files and the PC port. All SM64 and OoT projects since around 2015 have used SEQ64 (or some other program internally using it like N64 Sound Tools) for importing music, including PC port projects.

This is explained in [the very first FAQ near the top of the readme on the main page for SEQ64](https://github.com/sauraen/seq64#com-mus-what-is-all-this-where-do-i-load-a-rom). Assuming you are trying to convert a MIDI to .m64, simply click "Export .com / .aseq" in SEQ64 and select .m64 as the file extension.

**Comment by UnknownSkid** [comment]
> SEQ64 absolutely works with .m64 files and the PC port. All SM64 and OoT projects since around 2015 have used SEQ64 (or some other program internally using it like N64 Sound Tools) for importing music, including PC port projects.
> 
> This is explained in [the very first FAQ near the top of the readme on the main page for SEQ64](https://github.com/sauraen/seq64#com-mus-what-is-all-this-where-do-i-load-a-rom). Assuming you are trying to convert a MIDI to .m64, simply click "Export .com / .aseq" in SEQ64 and select .m64 as the file extension.

no i wanted to import a m64 file

**Comment by sauraen** [comment]
It sounds like you still have not read the readme or the wiki. Open SEQ64, click "Import .com / .aseq", select your ".m64" file, and it will import it.
