### ISSUE TITLE
.m64 import seems to be broken since V2.2.0

### ISSUE THREAD

**Issue by ghost** [sauraen/seq64#30]
Every version since **V2.2.0** is not able to import .m64 files properly, and I don't mean not able to properly export to MIDI either, the import itself errors out and is not correctly represented internally, so I can't even assembly edit the sequence.

The error seems to be "conflicting short/long notes".
Here's a [gist](https://gist.github.com/Fluvian/cbe62d2614bebcdb6baa872e713c0af0) comparing the output of the two versions.
Here's another [gist](https://gist.github.com/Fluvian/149350f01c7295f23026dd2f5041520b) for the debug output of the broken versions.

**Comment by sauraen** [comment]
Thanks for the bug report! I have put up a new release which fixes this bug and successfully imports your binary file. https://github.com/sauraen/seq64/releases/tag/2.3.2

For the record, this issue only arises when importing certain .com/.aseq binary files created by SEQ64, including the example you provided. Most .com/.aseq files are imported successfully with the program versions you mentioned, which is why this bug was not noticed until now.
