### ISSUE TITLE
How do you compile Seq64 on Mac?

### ISSUE THREAD

**Issue by ThePlayerRolo** [sauraen/seq64#32]
I've been wanting to make .m64 files for projects of mine for a little bit now, however I have no Idea how to use CMake and compile it for my Mac. So my question is how do you compile it for Mac as the Wiki doesn't help at all for someone like me.

**Comment by sauraen** [comment]
I have not tried to build seq64 on Mac for many years. But both the source and the build system are cross-platform so it should work. The process for building an application with CMake is very similar regardless of what the application is. Roughly the process should be:
- Install Xcode
- Install CMake
- Open CMake
- Select the seq64 top-level source folder as the source location
- Create a build folder somewhere and select it as the build location
- Click Configure
- If there are no errors, click Generate, then Open Project
- After the project has loaded in Xcode, find some menu command like Project > Build or something like this, and run that
- Find the seq64 application somewhere in nested folders in the build folder you created before

If there are problems, the most likely place they would occur is during the build, if the version of the Juce library I'm using is too old for your Mac.

**Comment by ThePlayerRolo** [comment]
what version of juce do you use?  Because everytime I download the zip, the juce folder is empty?

**Comment by sauraen** [comment]
The seq64 repo has Juce as a submodule. If you download the zip file, you'll only get my code, not Juce. You need to clone the repo with submodules enabled, then you will automatically get the right version of Juce: https://stackoverflow.com/questions/3796927/how-do-i-git-clone-a-repo-including-its-submodules

I have updated the wiki to clarify this.

**Comment by ThePlayerRolo** [comment]
So it mostly worked, except it says Cannot Find ABI folder, and whenever I click the edit button, it just does nothing. Other buttons work, just not that one. Is there anyway to fix it.  Update: After Checking with Xcode it says no file found whenever the edit button is pressed.

**Comment by sauraen** [comment]
seq64 searches for the ABI folder based on the running application, and in parent/sibling folders. So for example if the executable is
```
/a/b/c/d/e/seq64
```
it will look for the ABI folder in these paths until it finds it:
```
/a/b/c/d/e/abi/
/a/b/c/d/abi
/a/b/c/abi
/a/b/abi
/a/abi
/abi
```
However if seq64 is in `/a/b/c/f/g/seq64` and the ABI folder is in `/a/b/c/d/e/abi`, it will never find it. Normally, a CMake project is built in a `build` or `build_windows` folder in the repo root, so regardless of how deep within that folder the build system puts the executable,  it will eventually find the ABI at `/path/to/seq64_repo/abi`. However, if you made that build folder somewhere else, then that won't work. You'll need to copy seq64 itself to somewhere in the repo folder and try running it from there, or copy the ABI folder to somewhere near the build folder.

As far as the edit button, the button edits the selected ABI in the list box right next to it. Since there are no ABIs in the list box, there cannot be a selected ABI.

**Comment by ThePlayerRolo** [comment]
that worked thanks! Also is there anyway to export to .m64 (I need that specifcally for my project) Update: fixed it! just needted to change .com to .m64. THANKS FOR EVERYTHING YOU ARE AMAZING FOR SUPPORTING MAC! (Sorry but I'm just so happy rn)

**Comment by sauraen** [comment]
Glad it worked for you! Yes, the canonical Nintendo file extension for that file type is .com, and the old "community" extension was .aseq. But the SM64 community has used .m64 for that file type for a long time, even though that file extension was already taken for Mupen 64 TAS replay files. You can manually change the extension, but also there should be an option at the export step for what extension to export as. I'm not sure how that looks with the Mac style save-as box.
