### ISSUE TITLE
How to utilize the percussion part of the soundbank in SM64 Decomp?

### ISSUE THREAD

**Issue by ThePlayerRolo** [sauraen/seq64#35]
Basically SM64 Decomp has an instrument called "Percussion" in some soundbanks, However Idk how to use it, as the instrument is not listed with the other instruments, instead its null. Example:
[25.json](https://github.com/user-attachments/files/17091329/25.json)

**Comment by sauraen** [comment]
This is part of how General MIDI works. The "drums" or "percussion" is permanently assigned to channel 9 (if zero-indexed) / 10 (if one-indexed). The instrument assigned to that channel is always null because that channel will always play the percussion instead. Each note on that channel plays a different "percussion sound"--many of them are just repitched versions of the same sound, but there is more variety possible than with a regular instrument.

I recommend using SEQ64 to convert a couple vanilla sequences to MIDI and looking at them in your MIDI editor program to learn how they are constructed.

**Comment by ThePlayerRolo** [comment]
> This is part of how General MIDI works. The "drums" or "percussion" is permanently assigned to channel 9 (if zero-indexed) / 10 (if one-indexed). The instrument assigned to that channel is always null because that channel will always play the percussion instead. Each note on that channel plays a different "percussion sound"--many of them are just repitched versions of the same sound, but there is more variety possible than with a regular instrument.
> 
> I recommend using SEQ64 to convert a couple vanilla sequences to MIDI and looking at them in your MIDI editor program to learn how they are constructed.

How can I set my drums to Channel 9 in FL studio?

**Comment by sauraen** [comment]
> How can I set my drums to Channel 9 in FL studio?

I do not use or recommend FL Studio as a MIDI editor program. Nevertheless, much of the community continues to use it for that purpose, despite it being awkward to use it for that. I can't help you with this, you will have to look up documentation or tutorials.

If you are looking for alternative audio software which directly supports editing all properties of MIDIs relevant to SEQ64, I recommend Reaper.

**Comment by ThePlayerRolo** [comment]
> > How can I set my drums to Channel 9 in FL studio?
> 
> I do not use or recommend FL Studio as a MIDI editor program. Nevertheless, much of the community continues to use it for that purpose, despite it being awkward to use it for that. I can't help you with this, you will have to look up documentation or tutorials.
> 
> If you are looking for alternative audio software which directly supports editing all properties of MIDIs relevant to SEQ64, I recommend Reaper.

Update: I got Anvil Studio which allows me too edit channels directly after I got my new windows laptop.
