### ISSUE TITLE
Some channels die after a certain amount of time on a M64 I've been working on.

### ISSUE THREAD

**Issue by PablosCorner** [sauraen/seq64#4]
Hey, just wanted to report an issue I've been having that I haven't experienced until I started working on this particular M64. So I'm making a port of Emerald Coast (Act 1) from Sonic Adventure into SM64, but I've noticed that some channels just stop playing after a while. I'm not exactly sure why this is happening but if you want me to, I can send you the MIDI and M64 if you want to check it out yourself. Thanks!

**Comment by sauraen** [comment]
Sure, email them to me and I'll take a look. My email should be listed in the Help menu as well as in the readme.

**Comment by PablosCorner** [comment]
Alright, I sent it to your email.

**Comment by PablosCorner** [comment]
Any updates?

**Comment by sauraen** [comment]
Sorry, I'm very busy with grad school right now. I hope I can take a look at some point in the next week or so.

**Comment by PablosCorner** [comment]
Oh, it's no problem. Take your time.

**Comment by PablosCorner** [comment]
Sorry to bother you but have you found anything out?

**Comment by sauraen** [comment]
Really sorry, I've been very busy. I can't devote the time to this right now. Best of luck getting it working.

**Comment by Trenavix** [comment]
Hey, the problem here is with a custom loop point. A note cannot be touching the loop point. So for example, your note has a duration of 480 and touches the "section 1" line. Make it 479, and the channel will no longer mute after section 1 starts. This is a bug I noticed early on and just kind of dealt with it.

**Comment by sauraen** [comment]
Interesting. I will take a look at this, though I'm pretty busy recently so I can't promise it will be soon. I'm wondering if this is a bug in Nintendo's music engine, because I don't see any reason SEQ64 would just stop writing in notes after this. Still, if that is indeed the case, I need to make SEQ64 force notes to end 1 tick before section boundaries.

**Comment by sauraen** [comment]
Bug found and fixed. I had changed the handling of notes touching a section boundary in one place but forgot to change it in another place. Now notes may touch the section boundary without causing issues.
