### ISSUE TITLE
maybe some clarity in docs about relation (or lack of) to sequencer64 / seq24?

### ISSUE THREAD

**Issue by wolftune** [sauraen/seq64#5]
[seq24](http://filter24.org/seq24/about.html) is an outdated sequencing program, and https://github.com/ahlstromcj/sequencer64 is a currently-developed fork, which might be avoiding the "seq64" name to avoid conflict with your project.

All I know, is I was looking for that and came upon this. Both projects look interesting. Is there any relationship or just a name collision? I assume the latter.

Would it make any sense to add some "if you're looking for Sequencer64, the continuation of the old seq24, check out [link]" or similar?

**Comment by sauraen** [comment]
Thanks for letting me know that there's another project out there with a similar name. I don't really see it being an issue, since their project has nothing to do with N64 games or ROM hacking, and anyone seeing the readme on my project should know instantly that this wasn't what they were looking for. If the other project was using the name "seq64" it might be more of an issue, but in my project "SEQ64" doesn't stand for "Sequencer 64", if anything it stands for "Audioseq File Editor 64" or something like that.

**Comment by wolftune** [comment]
To be clear: the other project *is* somewhat using the exact name seq64, since seq24 was the original name. I was told about seq64 in reference to the other project, although it seems the formal name is sequencer64. Anyway, no worries, thanks for the note
