### ISSUE TITLE
Windows 32 version doesn't work.. On a Win32 computer!

### ISSUE THREAD

**Issue by MrMartley64** [sauraen/seq64#9]
Hello! I tried to open the 32 bit SEQ64 on a Windows XP Computer (Which is 32 bit). It said it wasn't a valid Win32 application. Basically, the 32 bit version doesn't work on a 32 bit computer

**Comment by sauraen** [comment]
Unfortunately, I believe the standard build tools of MSVC++ 2017 I'm using are compatible with Vista, 7, 8, and 10. I remember there was something about Windows XP 64 bit being supported, but I don't exactly remember. This is not essential to the operation of SEQ64 itself, it's about which version of the Windows libraries are used. Due to the outdatedness of Windows XP, I wouldn't consider this a high-priority issue.

Regarding the error message, Windows telling you that the executable is not valid doesn't mean that the number of bits are wrong, but that the Windows libraries are incompatible. Back when SEQ64 was built with MSVC++ 2015 (which didn't include Windows 10 support), people reported that when they tried to run the 64-bit build on Windows 10, it told them that the EXE was neither 64 bit nor 32 bit and therefore must be a 16-bit EXE from the MS-DOS days!

**Comment by sauraen** [comment]
Closing because as of SEQ64 V2.0, only 64-bit Windows and 64-bit Linux precompiled builds are distributed.
